opcao = int(input("Este é um conversor e decodificador de Código Morse.\n\n- Se você deseja converter uma mensagem para Código morse, digite \"1\".\n\n-Se seu desejo for decodificar uma mensagem do Código Morse para o alfabeto latino, digite \"2\".\n\n Opção: "))
if opcao == 1 :
	texto = input("Insira o texto que deseja converter para código Morse e convertê-lo-emos: ")
	barra = "𐰀"
	espaco = "𐰁"
	ponto = "𐰂"
	traco = "𐰃"
	morse = texto.replace("/", barra).replace(" ", espaco).replace(".", ponto).replace("-", traco).replace("1", ".---- ").replace("2", "..--- ").replace("3", "...-- ").replace("4", "....- ").replace("5", "..... ").replace("6", "-.... ").replace("7", "--... ").replace("8", "---.. ").replace("9", "----. ").replace("0", "----- ").replace(",", "--..-- ").replace("?", "..--.. ").replace("!", "-.-.-- ").replace("'", ".----. ").replace("\"", ".-..-. ").replace("(", "-.--. ").replace(")", "-.--.- ").replace("&", ".-... ").replace(":", "---... ").replace(";", "-.-.-. ").replace("_", "..--.- ").replace("=", "-...- ").replace("+", ".-.-. ").replace("$", "...-..- ").replace("@", ".--.-. ").replace("a", ".- ").replace("b", "-... ").replace("c", "-.-. ").replace("d", "-.. ").replace("e", ". ").replace("f", "..-. ").replace("g", "--. ").replace("h", ".... ").replace("i", ".. ").replace("j", ".--- ").replace("k", "-.- ").replace("l", ".-.. ").replace("m", "-- ").replace("n", "-. ").replace("o", "--- ").replace("p", ".--. ").replace("q", "--.- ").replace("r", ".-. ").replace("s", "... ").replace("t", "- ").replace("u", "..- ").replace("v", "...- ").replace("w", ".-- ").replace("x", "-..- ").replace("y", "-.-- ").replace("z", "--.. ").replace("A", ".- ").replace("B", "-... ").replace("C", "-.-. ").replace("D", "-.. ").replace("E", ". ").replace("F", "..-. ").replace("G", "--. ").replace("H", ".... ").replace("I", ".. ").replace("J", ".--- ").replace("K", "-.- ").replace("L", ".-.. ").replace("M", "-- ").replace("N", "-. ").replace("O", "--- ").replace("P", ".--. ").replace("Q", "--.- ").replace("R", ".-. ").replace("S", "... ").replace("T", "- ").replace("U", "..- ").replace("V", "...- ").replace("W", ".-- ").replace("X", "-..- ").replace("Y", "-.-- ").replace("Z", "--.. ").replace(barra, "-..-. ").replace(espaco, "/ ").replace(ponto, ".-.-.- ").replace(traco, "-....- ").replace("á", ".- ").replace("à", ".- ").replace("â", ".- ").replace("À", ".- ").replace("Á", ".- ").replace("Â", ".- ").replace("ã", ".- ").replace("Ã", ".- ").replace("Ç", "-.-. ").replace("ç", "-.-. ").replace("é", ". ").replace("É", ". ").replace("ê", ". ").replace("Ê", ". ").replace("è", ". ").replace("é", ". ").replace("ẽ", ". ").replace("Ẽ", ". ").replace("í", ".. ").replace("Í", ".. ").replace("ì", ".. ").replace("Ì", ".. ").replace("ĩ", ".. ").replace("Ĩ", ".. ").replace("î", ".. ").replace("Î", ".. ").replace("ñ", "-. ").replace("Ñ", "-. ").replace("ó", "--- ").replace("Ó", "--- ").replace("ò", "--- ").replace("Ò", "--- ").replace("ô", "--- ").replace("Ô", "--- ").replace("õ", "--- ").replace("Õ", "--- ").replace("ú", "..- ").replace("Ú", "..- ").replace("ù", "..- ").replace("Ù", "..- ").replace("û", "..- ").replace("Û", "..- ").replace("ũ", "..- ").replace("Ũ", "..- ")
	print(morse)
elif opcao == 2:
	texto = input("Insira o texto que deseja decodificar: ")
	print(texto.replace(" / ", "ѥ").replace("..--..", "?").replace("..--.-", "_").replace(".-..-.", "''").replace(".-.-.-", "Ш").replace(".--.-.", "@").replace(".----.", "'").replace("-....-", "Ж").replace("-.-.-.", ";").replace("-.-.--", "!").replace("-.--.-", ")").replace("--..--", ",").replace("---...", ":").replace(".----", "1").replace("..---", "2").replace("...--", "3").replace("....-", "4").replace(".....", "5").replace("-....", "6").replace("--...", "7").replace("---..", "8").replace("----.", "9").replace("-----", "0").replace(".-.-.", "+").replace("-...-", "=").replace("....", "H").replace("...-", "V").replace("..-.", "F").replace(".-..", "L").replace(".--.", "P").replace(".---", "J").replace("-...", "B").replace("-..-", "X").replace("-.-.", "C").replace("-.--", "Y").replace("--..", "Z").replace("--.-", "Q").replace("...", "S").replace("..-", "U").replace(".-.", "R").replace(".--", "W").replace("-..", "D").replace("-.-", "K").replace("--.", "G").replace("---", "O").replace("..", "I").replace(".-", "A").replace("-.", "N").replace("--", "M").replace(".", "E").replace("-", "T").replace("Ш", ".").replace("Ж", "-").replace(" ", "").replace("ѥ", " "))
